### ISSUE TITLE
[Calendar] Дни недели

### ISSUE THREAD

**Issue by pavel-b-novikov** [ffloxee/nsudotnet#1]
Не должны быть захардкожены

**Comment by ffloxee** [comment]
Исправила все, о чем Вы написали.
Надеюсь, правильно поняла Ваши замечания.

**Comment by pavel-b-novikov** [comment]
Отпишитесь к каждому замечанию отдельно, пожалуйста.

**Comment by ffloxee** [comment]
Исправила свои захардкоженые дни недели

**Comment by pavel-b-novikov** [comment]
Ну если для исправления вы все еще вбивали дни недели руками (через enum), то это не исправление.

**Comment by ffloxee** [comment]
Проверьте, пожалуйста. Минимум "хардкодинга" в днях недели.

**Comment by pavel-b-novikov** [comment]
Ну наконец-то, хоть так.
