### ISSUE TITLE
[Calendar] .Equals

### ISSUE THREAD

**Issue by pavel-b-novikov** [ffloxee/nsudotnet#2]
Я понимаю когда люди сравнивают строки через .Equals - ну да, тяжелое наследие java, но...
`today.Month.Equals(date.Month)`

Это что-то новенькое

**Comment by ffloxee** [comment]
Исправила. 
Но ведь на практике сработает и через today.Month.Equals(date.Month), и через today.Month == date.Month

**Comment by pavel-b-novikov** [comment]
Да, но за первое вас тапками закидают, а за второе - нет.
