### ISSUE TITLE
[Calendar] switch (count)

### ISSUE THREAD

**Issue by pavel-b-novikov** [ffloxee/nsudotnet#4]
Я вообще не въехал в этот кусок кода. Он вообще работает?

**Comment by ffloxee** [comment]
Конечно, работает. Как минимум, для выделения выходных дней в календаре

**Comment by pavel-b-novikov** [comment]
А, у вас count обнуляется, вижу.
слушайте, а вот как-то итерироваться не по интам, а по датам - слабо? И свитч делать по DayOfWeek - нет?

**Comment by ffloxee** [comment]
В switch count - это не конкретный день недели. Мне надо тогда целиком убирать switch и переписывать, если Вам не нравится эта конструкция с интами.
Вам это так сильно режет глаза?

**Comment by pavel-b-novikov** [comment]
Да, мне именно так сильно режет глаза, потому как создается ощущение, что вы сделали count из-за незнания что можно делать switch по enum-ам.

**Comment by ffloxee** [comment]
Исправила switch
