### ISSUE TITLE
[Rss2Email] Диспоз

### ISSUE THREAD

**Issue by pavel-b-novikov** [ffloxee/nsudotnet#7]
в задаче не все диспозится. Пожалуйста, найдите все места и поправьте. Мне отпишитесь.

**Comment by ffloxee** [comment]
Задиспозила SmtpClient и MailMessage. Вроде ничего не забыла.

**Comment by pavel-b-novikov** [comment]
Вызов .Dispose вы называете "задиспозила"? Вы не правы.

**Comment by ffloxee** [comment]
Тогда не могли бы Вы, пожалуйста, пояснить, что Вы называете "диспозить"?

**Comment by pavel-b-novikov** [comment]
У вас сейчас 4 балла. За такие вопросы в конце семестра, учитывая что на курс вас силой никто не тащил, трояка в зачетке вам будет достаточно.

**Comment by ffloxee** [comment]
И все-таки я не согласна с такой оценкой. Вы хотите, чтобы я закрывала потоки? Или есть какие-то необработанные случаи с исключениями?

**Comment by pavel-b-novikov** [comment]
Нет, я категорически не могу понять людей, для которых я каждую среду проводил лекции по 3 часа, на которых детально объяснял и показывать что к чему, в чем проблематика и как писать правильно. Я объяснял и синтаксис и идиоматику. Крупными буквами при том, во весь слайд. Если вы не ходите на лекции - предполагается, что вы этот материал изучаете сами. Если вы не смогли изучить его сами и задаете насколько глупые вопросы - то увы, у меня сейчас нет ни времени ни желания вас чему-либо учить в индивидуальном порядке. Поэтому с вашей оценкой я категорически согласен.

**Comment by ffloxee** [comment]
Я до сих пор не смогла понять, что вы подразумеваете под этим словом и что Вас не устраивает в моем решении. Очень жаль. Но спорить с Вами не буду.

**Comment by pavel-b-novikov** [comment]
Я уверен, однокурсники вам объяснят лучше.
